FROM node:16-alpine AS development

ENV NODE_ENV development

LABEL maintainer="Ashwani Kumar Kamal (sneaky-potato) <ashwanikamal.im421@gmail.com>"

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn install

COPY . .

EXPOSE 3000

CMD [ "yarn", "start" ]